backend/models/Article.php
<?php
namespace backend\models;

use Yii;
use common\models\Article as _Article;

/**
 *
 */
class Article extends _Article
{
    /**
     * @var int
     */
    public $createdAtFilter;
    /**
     * @var int
     */
    public $updatedAtFilter;
    /**
     * @var string
     */
    public $userEmailFilter;
}

common/models/Article.php
<?php
namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "article".
 *
 * @property string  $id
 * @property string  $title
 * @property string  $text
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $user_id
 * @property string  $description
 * @property string  $preview_text
 * @property string  $preview_image
 * @property integer $status
 * @property string  $previewImagePath
 *
 * @property User    $user
 */
class Article extends ActiveRecord
{
    const PATH = '/article/';

    const STATUS_ACTIVE = 10;
    const STATUS_DRAFT  = 0;

    private $_pathUrl;
    private $_pathRoot;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text', 'preview_text'], 'string'],
            ['status', 'in', 'range' => [static::STATUS_DRAFT, static::STATUS_ACTIVE]],
            [['created_at', 'updated_at', 'user_id'], 'integer'],
            [['user_id'], 'required'],
            [['title', 'description', 'preview_image'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'            => 'ID',
            'title'         => 'Title',
            'text'          => 'Text',
            'created_at'    => 'Created At',
            'updated_at'    => 'Updated At',
            'user_id'       => 'User ID',
            'description'   => 'Description',
            'preview_text'  => 'Preview Text',
            'preview_image' => 'Preview Image',
        ];
    }

    /**
     * Получить полный путь к картинке
     *
     * @param bool $isUrl URL или путь в файловой системе(false)
     *
     * @return null|string
     */
    public function getPreviewImagePath($isUrl = true)
    {
        if ( !$this->preview_image) return null;
        if ($isUrl) {
            if ( !$this->_pathUrl) {
                $this->_pathUrl = Yii::getAlias('@images' . static::PATH . $this->preview_image);
            }

            return $this->_pathUrl;
        } else {
            if ( !$this->_pathRoot) {
                $this->_pathRoot = Yii::getAlias('@imagesroot' . static::PATH . $this->preview_image);
            }

            return $this->_pathRoot;
        }
    }

    /**
     * Generate unique fit image name.
     * If the name exists, it will be not regenerate
     *
     * @param string $ext image file extension
     *
     * @return string name
     */
    public function generatePreviewImageName($ext)
    {
        if ($this->preview_image) return $this->preview_image;

        do // generate unique name
        {
            $name = Yii::$app->getSecurity()
                             ->generateRandomString(30) . ".$ext";
        } while (static::findOne(['preview_image' => $name])); // if exists - regenerate

        $this->preview_image = $name;
        return $name;
    } // end generateName()

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}

backend/controllers/ArticleController.php
<?php

namespace backend\controllers;

use backend\models\ArticleCreate;
use backend\models\ArticleUpdate;
use kartik\helpers\Html;
use Yii;
use backend\models\Article;
use backend\models\ArticleSearch;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $post = Yii::$app->request->post();

        if (Yii::$app->request->isAjax && isset($post['kvdelete'])) {
            if ($model && $model->delete()) {
                echo Json::encode([
                    'success'  => true,
                    'messages' => [
                        'kv-detail-info' => 'The article # ' . $model->id . ' was successfully deleted. ' . Html::a('<i class="glyphicon glyphicon-hand-right"></i>  Click here',
                                ['/article/index'], ['class' => 'btn btn-sm btn-info']) . ' to proceed.'
                    ]
                ]);
            } else {
                echo Json::encode([
                    'success'  => false,
                    'messages' => [
                        'kv-detail-warning' => 'Can not delete article',
                    ]
                ]);
            }
            return;
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ArticleCreate();

        if ($model->load(Yii::$app->request->post())) {
            $model->previewImageFile = UploadedFile::getInstance($model, 'previewImageFile');

            $article = $model->create();
            if ($article) {
                return $this->redirect(['view', 'id' => $article->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param string $id
     *
     * @return mixed
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = ArticleUpdate::findOne($id);
        if ($model === null) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        $model->scenario = ArticleUpdate::SCENARIO_UPDATE;
        if ($model->load(Yii::$app->request->post())) {
            $model->previewImageFile = UploadedFile::getInstance($model, 'previewImageFile');

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/article/_form.php
<?php

use backend\models\Article;
use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditor;

/* @var $this      yii\web\View */
/* @var $model     backend\models\ArticleCreate|backend\models\ArticleUpdate */
/* @var $form      yii\widgets\ActiveForm */
/* @var $isNew     boolean */
/* @var $labelSpan integer */
?>

<div class="article-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'],
        'type' => ActiveForm::TYPE_HORIZONTAL,
        'formConfig' => ['labelSpan' => $labelSpan, 'deviceSize' => ActiveForm::SIZE_SMALL]
    ]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'text')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'full'
    ]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'preview_text')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'basic'
    ]) ?>


    <?php if (!$isNew): ?>
        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <?= Html::img($model->previewImagePath, ['style' => 'width: 400px']) ?>
            </div>
        </div>
    <?php endif ?>
    <?= $form->field($model, 'previewImageFile')->fileInput()->label('Update preview image') ?>

    <?= $form->field($model, 'status')->dropDownList([
        Article::STATUS_ACTIVE => 'Активна',
        Article::STATUS_DRAFT  => 'Набросок',
    ]) ?>

    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <?= Html::submitButton($isNew ? 'Create' : 'Update', ['class' => $isNew ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/article/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\ArticleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'text') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'preview_text') ?>

    <?php // echo $form->field($model, 'preview_image') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/article/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Article */

$this->title = 'Create Article';
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create">

    <div class="row">
        <h1 class="col-sm-10 col-sm-offset-2">
            <?= Html::encode($this->title) ?>
        </h1>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
        'isNew' => true,
        'labelSpan' => 2,
    ]) ?>

</div>

backend/views/article/index.php
<?php
use kartik\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ArticleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                   = 'Articles';
$this->params['breadcrumbs'][] = $this->title;

$columns = [
    'id',
    'title',
    'description',
    [
        'attribute' => 'createdAtFilter',
        'value'     => 'created_at',
        'format'    => ['date', 'php:Y-m-d'],

        'width'               => '200px',
        'filterType'          => GridView::FILTER_DATE,
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'format'         => 'yyyy-mm-dd',
                'autoclose'      => true,
                'todayHighlight' => true,
            ],
        ],
    ],
    [
        'attribute' => 'updatedAtFilter',
        'value'     => 'updated_at',
        'format'    => ['date', 'php:Y-m-d'],

        'width'               => '200px',
        'filterType'          => GridView::FILTER_DATE,
        'filterWidgetOptions' => [
            'pluginOptions' => [
                'format'         => 'yyyy-mm-dd',
                'autoclose'      => true,
                'todayHighlight' => true,
            ],
        ],
    ],
    [
        'attribute' => 'userEmailFilter',
        'value'     => 'user.email',
    ],
    [
        'label'  => 'Preview Image',
        'format' => 'html',
        'mergeHeader' => true,
        'value' => function ($model) {
            return Html::img($model->previewImagePath, [
                'alt'   => 'Картинка в Grid View',
                'style' => 'width: 100px',
            ]);
        },
    ],

    ['class' => 'kartik\grid\ActionColumn'],
];
?>
<div class="article-index">

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel'  => $searchModel,

        'pjax' => true,

        'panel' => [
            'type'    => GridView::TYPE_DEFAULT,
            'heading' => 'Users',
            'before'  => Html::a('<i class="glyphicon glyphicon-plus"></i> Create an article', ['create'],
                ['class' => 'btn btn-success']),
            'after'   => false,
        ],

        'columns' => $columns,
    ]); ?>

</div>

backend/views/article/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Article */

$this->title = 'Update Article: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="article-update">

    <div class="row">
        <h1 class="col-sm-10 col-sm-offset-2">
            <?= Html::encode($this->title) ?>
        </h1>
    </div>

    <?= $this->render('_form', [
        'model'     => $model,
        'isNew'     => false,
        'labelSpan' => 2,
    ]) ?>

</div>

backend/views/article/view.php
<?php

use kartik\detail\DetailView;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this  yii\web\View */
/* @var $model common\models\Article */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$attributes = [
    'id',
    [
        'attribute' => 'created_at',
        'format' => ['date', 'php:Y-m-d'],
    ],
    [
        'attribute' => 'updated_at',
        'format' => ['date', 'php:Y-m-d'],
    ],
    [
        'attribute' => 'user_id',
        'label' => 'Author ID',
    ],
    [
        'label' => 'Author E-mail',
        'value' => $model->user->email,
    ],
    'title',
    'text:html',
    'description',
    'preview_text:html',
    [
        'label' => 'Preview Image',
        'format' => 'html',
        'value' => Html::img($model->previewImagePath, ['style' => 'width: 400px']),
        'style' => 'width: 100px'
//        'preview_image',
    ],
];
?>
<div class="article-view">

    <p>
        <?php /* = Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) */ ?>
    </p>

    <?= DetailView::widget([
        'model'      => $model,
        'condensed'  => true,
        'hover'      => true,
        'mode'       => DetailView::MODE_VIEW,
        'buttons1' => '{delete}',
        'panel'      => [
            'heading' => 'Article: ' . $model->title,
            'type'    => DetailView::TYPE_INFO,
        ],
       'deleteOptions' => [
           'params' => ['id' => $model->id, 'kvdelete'=>1],
//           'url' => Url::toRoute(['/article/delete', 'id' => $model->id]),
       ],
       'attributes' => $attributes,
    ]) ?>

</div>